services:
  - type: web
    name: fuvani-django
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn mysite.wsgi:application
    postDeployCommand: python manage.py migrate
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mysite.settings
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com,fuvani.com,www.fuvani.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com,https://fuvani.com,https://www.fuvani.com
