services:
  - type: web
    name: welcome-page
    env: python
    rootDir: .
    buildCommand: >
      export PYTHONPATH=/opt/render/project/src &&
      pip install -r requirements.txt &&
      DJANGO_SETTINGS_MODULE=mysite.settings python -m django collectstatic --noinput
    startCommand: >
      export PYTHONPATH=/opt/render/project/src &&
      gunicorn mysite.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.6
